---
CRNT_OS_CONF_PATH: "/opt/opensearch-2.4.1/config" #The current opensearch config path
OLD_OS_VERSION: "2.4.1" #The current opensearch version
NEW_OS_VERSION: "2.15.0" #Change to the version you want to upgrade to
OS_USER: opensearch
OS_GROUP: opensearch