---
  - ansible.builtin.import_tasks: disableShardAllocation.yml
    tags: disableShardAllocation

  - ansible.builtin.import_tasks: stopOpensearch.yml
    tags: stopOpensearch

  - ansible.builtin.import_tasks: downloadTarball.yml
    tags: downloadTarball

  - ansible.builtin.import_tasks: extractTarballFile.yml
    tags: extractTarballFile      

  - import_tasks: copyConfigFiles.yml
    tags: copyConfigFiles

  - import_tasks: addCompatibilitySettings.yml
    tags: addCompatibilitySettings

  - import_tasks: changePermissionAndOwnership.yml
    tags: changePermissionAndOwnership

  - import_tasks: correctPaths.yml
    tags: correctPaths

  - import_tasks: serviceFilePath.yml
    tags: serviceFilePath

  - import_tasks: changeSystemdFile.yml
    tags: changeSystemdFile

  - import_tasks: daemonReload.yml
    tags: daemonReload
  
  - import_tasks: startOpensearchService.yml
    tags: startOpensearchService

  - import_tasks: enableShardAllocation.yml
    tags: enableShardAllocation

  - import_tasks: nodeJoinedCluster.yml
    tags: nodeJoinedCluster