---
  - name: daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: start opensearch
    ansible.builtin.service:
      name: opensearch
      state: started

  - name: stop opensearch
    ansible.builtin.service:
      name: opensearch
      state: stopped